### ISSUE TITLE
Copy Button

### ISSUE THREAD

**Issue by smaragdus** [shevabam/get-rss-feed-url-extension#11]
I would like to suggest a tiny enhancement for [Get RSS Feed URL](https://github.com/shevabam/get-rss-feed-url-extension)- a new button:

- **Copy**

which copies the selected link.

I will provide an example with a similar extension- **RSS Finder** ([Chrome Web Store](https://chrome.google.com/webstore/detail/rss-finder/cdjocoacgphmbihenkkgaackgkjlfncp)) which has such **Copy** button, screen:

![RSS Finder 2 0 0 - 2020-04-07 - 002](https://user-images.githubusercontent.com/9025757/78669189-8d7ede80-78e4-11ea-8036-ec23edb93bc0.png)

If implemented, such **Copy** button would spare the user a few clicks (right click + Copy link address).

A further improvement would be:

- **Copy All**

button (perhaps below the links) which copies all detected links.

**Comment by shevabam** [comment]
Hello,
Thank you for your detailed feedback!
It's a very good idea, I'll try to implement it quickly.

**Comment by smaragdus** [comment]
@shevabam 

Thank you for considering my suggestion.

Best regards

**Comment by shevabam** [comment]
I added the "copy" button for each detected feed!
The publication of the new version (1.3.0) may take some time on the store...

**Comment by smaragdus** [comment]
@shevabam 

Hello,

I got version **1.3.1** via [Chrome Web Store](https://chrome.google.com/webstore/detail/get-rss-feed-url/kfghpdldaipanmkhfpdcjglncmilendn) but it does not work for me- I see the moving dots showing that the extension is searching for RSS links, screens:

![Get RSS Feed URL 1 3 1 - 004](https://user-images.githubusercontent.com/9025757/79000753-e1442e80-7b55-11ea-9bdc-4530eb290949.png)

![Get RSS Feed URL 1 3 1 - 002](https://user-images.githubusercontent.com/9025757/79000809-fde06680-7b55-11ea-80b8-ac54c331198c.png)

But the operation never completes. I tried version **1.3.1** with several websites but it never managed to get the RSS links. Are you sure that version **1.3.1** is not buggy? Or the problem is with my browser? Until today [Get RSS Feed URL](https://github.com/shevabam/get-rss-feed-url-extension) was always working just fine for me.

Regards

**Comment by shevabam** [comment]
The extension works perfectly for me on several computers.
On which sites are you trying to get RSS feeds?

**Comment by smaragdus** [comment]
@shevabam 

The mystery is solved. I was using [Cent Browser](https://www.centbrowser.com/) [version](https://www.centbrowser.com/history.html) **4.1.7.182** which is based on **Chromium** version **78.0.3904.108**. After I updated to version **4.2.9.152** which is based on **Chromium** version **80.0.3987.163** [Get RSS Feed URL](https://github.com/shevabam/get-rss-feed-url-extension) version **1.3.1** works just fine, screen:

![Get RSS Feed URL 1 3 1 - 006](https://user-images.githubusercontent.com/9025757/79004897-51ef4900-7b5e-11ea-8b83-d92ebe1424b1.png)

which means that version **1.3.1** is incompatible with previous versions of **Chromium**.

Thanks for adding **Copy URL** button!

Last question on this topic- you did not like the idea to add **Copy All URLs** button?

**Comment by shevabam** [comment]
Nice!
For the "copy all URLs button", you'll use this in what purpose?
Which separator should there be between URLs?

**Comment by smaragdus** [comment]
@shevabam 

First I would like to thank you for maintaining this extension which is extremely useful for me! Browsers not supporting RSS natively is a shame but this is another topic.

> For the "copy all URLs button", you'll use this in what purpose?

I started building a RSS database using a text file with simple structure:

- Website name
- Website link
- RSS link(s)

mainly to easily transfer list of feeds from my computer to my phone. I am not using OPML files exported from my desktop RSS readers because I usually read different stuff on PC and phone.

> Which separator should there be between URLs?

I don't need separators, new line for every RSS link would be enough, example:

- RSS link 1
- RSS link 2
- RSS link 3

But as I use a clipboard manager copying all links manually (when needed) won't be a problem. If you think that such 'Copy All URLs' button would not be of great value for most users of your extension discard the idea. Yet I think that in some rare cases such 'Copy All URLs' button might be useful.

Regards

**Comment by shevabam** [comment]
Hello,
Thank you for your reply.
I added a "Copy all URLs" link at the bottom of the results. This button copies the different URLs found one below the other.

The publication of the new version (1.3.2) may take some time on the store.

**Comment by smaragdus** [comment]
@shevabam 

> I added a "Copy all URLs" link at the bottom of the results. This button copies the different URLs found one below the other.

This is excellent! Thank you for your great kindness! I hope that the extension will soon be updated on [Chrome Web Store](https://chrome.google.com/webstore/detail/get-rss-feed-url/kfghpdldaipanmkhfpdcjglncmilendn). I wish you sincerely all the best not just because you implemented all the features that I suggested but because you are so nice and helpful!

**BIG THANK YOU!**

Best regards

**Comment by smaragdus** [comment]
@shevabam 

I got version **1.3.2** and it looks and works nice, screen:

![Get RSS Feed URL 1 3 2 - 2020-04-15 - 002](https://user-images.githubusercontent.com/9025757/79362413-3cf42a80-7f4f-11ea-8f89-1c46599ea1d1.png)

I am completely satisfied with your extension! Many thanks for **Copy all URLs** button, it will be very helpful for my use sparing me a few clicks.

Best regards

**Comment by shevabam** [comment]
Thank you very much for your remarks and comments! It's very motivating!
I'm glad the changes are right for you!
