### ISSUE TITLE
Feature Request: Add /feed check

### ISSUE THREAD

**Issue by sunk818** [shevabam/get-rss-feed-url-extension#12]
It seems this extension is missing some RSS feed URLs that is not in the current page, but may be a site URL. For example, no RSS feed is detected for fortune.com but there is a fortune.com/feed that works.

**Comment by reekes** [comment]
Why doesn't it find the obvious RSS feed for this site?
https://historynewsnetwork.org/

**Comment by shevabam** [comment]
Hello,

Websites do not always put the link to the RSS feed where it is needed in the source code. It is, however, an HTML standard but which is not respected very much in the end.

I modified the extension to try to find an RSS feed by checking the pages "site.com/feed", "site.com/rss", "site.com/feed.xml" and "site.com/rss.xml ".

It now works for several sites including fortune.com and historynewsnetwork.org!

The publication of the new version (1.3.2) may take some time on the store.
