### ISSUE TITLE
Incorrect RSS feed url deduction

### ISSUE THREAD

**Issue by jfrech** [shevabam/get-rss-feed-url-extension#13]
When relatively referencing an `rss.xml` document, e. g.

    <link rel="alternate" type="application/rss+xml" href="rss.xml">

the RSS feed url includes the html file where it was referenced, i. e. `https://www.website.com/index.html/rss.xml` instead of `https://www.website.com/rss.xml`.

I think the issue lies in the following line, where `url` should be trimmed (e. g. by replacing it with `url.replace(/\/[^/]*$/, '')`).
https://github.com/shevabam/get-rss-feed-url-extension/blob/33ff05628c5c18c0476693d765243fc7dff7cb41/js/popup.js#L88

**Comment by shevabam** [comment]
Hi,
Do you have a site with this example?

**Comment by jfrech** [comment]
@shevabam I built a [demonstration](https://www.jfrech.com/get-rss-feed-url-extension_test/test.html).

**Comment by shevabam** [comment]
Hello,
Thank you ! I was able to improve the detection of the RSS feed URL.
v1.3.3 is being released on the Chrome Extensions Store.
