### ISSUE TITLE
Add the URL below RSS feeds

### ISSUE THREAD

**Issue by barbudo2005** [shevabam/get-rss-feed-url-extension#14]
Could you add the URL below the RSS feeds to see which is the best to apply, like this:

![image](https://user-images.githubusercontent.com/59028314/84576969-fbd19880-ad8e-11ea-90bb-57de3a69623b.png)

Thank you very much in advance

**Comment by shevabam** [comment]
Hi,
Would it be nice like that?
![2020-06-15_20h22_16](https://user-images.githubusercontent.com/1798289/84692389-1437e380-af46-11ea-8eb1-24fd119792be.png)

**Comment by barbudo2005** [comment]
Fantastic. Thank you very much.

Another very useful improvement would be:

Page without feeds : Icon of the extension grayscale.
Page with feeds : Normal icon

**Comment by shevabam** [comment]
Hello,
Thank you ! I added the full URL of the RSS feed.
v1.3.3 is being released on the Chrome Extensions Store.

Regarding the activation of the icon or not, another request exists #6. I haven't found a solution yet!
