### ISSUE TITLE
Display a badge with the number of feeds detected

### ISSUE THREAD

**Issue by n-peugnet** [shevabam/get-rss-feed-url-extension#15]
This could be achieved using the [browserAction badge](https://developer.chrome.com/extensions/browserAction#badge) and would be a really cool addition IMO. This issue is related to #6 as the purpose of both features is to add visual information to the icon, but I think that the badge is as easy to implement and at the same time gives a lot more information.

**Comment by shevabam** [comment]
Hi,
The new version 1.4 brings this functionality.
It is currently being published on the store.
Thank you !

**Comment by shevabam** [comment]
This feature causes loading errors on some websites. 
I had to remove it for now, while I figured out how to fix the problem.
Thank you for your understanding.
