### ISSUE TITLE
Spyware?  

### ISSUE THREAD

**Issue by archerships** [shevabam/get-rss-feed-url-extension#20]
Saw this in the reviews for the extension: 

Works, but it was doing something strange to my google searches.  It was redirecting google search result links through https://sr.gdprvalidate.de/redir/clickGate.php?...  Strange... acting like spyware...  comments, developer?

**Comment by shevabam** [comment]
Hello,
The extension does not redirect to any site. It simply retrieves the source code of the visited site to find RSS feeds.
