### ISSUE TITLE
Need "manially re-enable" for functioning

### ISSUE THREAD

**Issue by piyavking** [shevabam/get-rss-feed-url-extension#28]
I launch firefox (102.8.0esr), and add-on (installed from mozilla add-on store) only start functioning if I manually turn them off and on again in the add-on manager...

**Comment by shevabam** [comment]
Hello,
I am not the author of the Mozilla Firefox add-on

**Comment by Korb** [comment]
@CodeCubeNeo, @piyavking, you can report the [Get RSS Feed URL by Petr](https://addons.mozilla.org/en-US/firefox/addon/get-rss-feed-url/) as being posted without the permission of the original extension's author, and impersonating it by linking to this repository.
