### ISSUE TITLE
Get YouTube Feeds

### ISSUE THREAD

**Issue by Templarfreak** [shevabam/get-rss-feed-url-extension#3]
For most channels, it's as simple as pasting the YouTube's channel ID at the end of this:

"https://www.youtube.com/feeds/videos.xml?channel_id="

For example, this would be the feed to the Vsauce DONGs channel: 

https://www.youtube.com/feeds/videos.xml?channel_id=UClq42foiSgl7sSpLupnugGA

Usually, you can get that just from the Channel's URL. For instance: https://www.youtube.com/channel/UClq42foiSgl7sSpLupnugGA

But some channels aren't a "Channel" they're a "User", like Film Theorists:

https://www.youtube.com/user/FilmTheorists

Users aren't a channel so they don't have a Channel ID, but a User still has a corresponding Channel that **does** have a Channel ID, and this is where the videos **actually** get uploaded to when a User uploads a video.

http://johnnythetank.github.io/youtube-channel-name-converter/

By imputing the link there, it's possible to get the channel ID: UC3sznuotAs2ohg_U__Jzj_Q

For the FIlm Theorists.

I'm not really sure of the exact science behind the converter, though.

Every single Channel **does** have a corresponding RSS Feed URL and every single User has a corresponding channel. They are automatically generated with these.

**Comment by shevabam** [comment]
Hello,

Done!
Thanks ;)

**Comment by Templarfreak** [comment]
this is, like, 5 years old. YouTube has since made many, many under-the-hood changes that probably make this exact method i outlined here no longer work, however it does look like the RSS Feeds i had posted in OP do still work, so, idk. doesnt really matter anyway, because YouTube intentionally doesnt sound out updates for their RSS Feeds very quickly at all anymore. getting uploads from a channel can take hours to _days._

**Comment by bepolymathe** [comment]
Thank you for your reply.
