### ISSUE TITLE
href addresses that start with "/" should be appended to the host name (not the whole URI)

### ISSUE THREAD

**Issue by fldef** [shevabam/get-rss-feed-url-extension#4]
I ran into this problem on https://www.scala-lang.org/ . The links appear on each page as such: 

```
<link rel="alternate" type="application/atom+xml" title="News Feed" href="/feed/index.xml" />
<link rel="alternate" type="application/atom+xml" title="Blog Feed" href="/feed/blog.xml" />
```

The absolute addresses, respectively:
https://www.scala-lang.org/feed/index.xml
https://www.scala-lang.org/feed/blog.xml

The extension works as expected when launched from the home page. However, when launched from https://www.scala-lang.org/blog/ , the links are incorrect:

https://www.scala-lang.org/blog//feed/index.xml
https://www.scala-lang.org/blog//feed/blog.xml

It seems the extension is not testing for root-relative addresses.

**Comment by shevabam** [comment]
Hi,

Thanks for your report!
I made a modification, could you update your extension in version 1.2.2?

**Comment by fldef** [comment]
I updated to 1.2.2 and it works as expected. Thanks for your help.
