### ISSUE TITLE
Not working on most of the websites

### ISSUE THREAD

**Issue by sumt7** [shevabam/get-rss-feed-url-extension#5]
Not working on almost every website.

Screengrab http://prntscr.com/jwd65q
![image](https://user-images.githubusercontent.com/9494546/41548588-01e35ff4-7341-11e8-8ab0-e51cb0414774.png)

**Comment by shevabam** [comment]
Hi,

On this website, there is no tag referring to the RSS feed in the HEAD tag.
So the extension can not retrieve the URL of the RSS feed.

Can you give me other examples of websites for which the extension does not work?
Thanks.

**Comment by sumt7** [comment]
Hi there,

It seems that those tags aren't available on many world famous websites
I've mentioned below or maybe there's a serious fault in your chrome
extension.

[image: image.png]

[image: image.png]



[image: image.png]
















Best Wishes,
*Sumeet Mahendra*
www.bit.ly/sumt7p

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/18/18,
11:50:16 PM

**Comment by shevabam** [comment]
I checked on the sites mentioned, actually, they do not put the link to the RSS feed in the standardized ballise (eg `<link rel="alternate "type="application/rss+xml" href="http: //example.com/feed"/>`).
The extension works well, it just retrieves URLs in `<link>` tags.
Many news sites do not put forward the RSS feed, and it's a shame ...

**Comment by sumt7** [comment]
Yeah, is there's anything we can do from our end. As we're looking for RSS
and Atom urls to integrate on IFTTT and Zapier.

Best,
Sumeet Mahendra
about.me/sumt7
