### ISSUE TITLE
Feature Request: Light up when a link is found and turn off otherwise 

### ISSUE THREAD

**Issue by SiqingYu** [shevabam/get-rss-feed-url-extension#6]
Like in https://github.com/justinkelly/chrome-rss
The extension can run in the background when the webpage is opened and get the RSS feeds.
If no link is found, then it is greyed out. If it finds a link, then it lights up the orange logo.
This way the user will immediately know if there is an RSS feed link or not.

**Comment by wokawoka** [comment]
I agree, it would be a very useful addition

**Comment by p3ngwin** [comment]
+1 this would be great.

**Comment by shevabam** [comment]
Hi,
The new version 1.4 brings this functionality.
It is currently being published on the store.
Thank you !

**Comment by p3ngwin** [comment]
Fantastic news, thank you !
