### ISSUE TITLE
You app do not seem to pick all feeds 

### ISSUE THREAD

**Issue by Ainz** [shevabam/get-rss-feed-url-extension#8]
Hi, 
I got your app to follow up on feeds that may be hard to find the URL for, exactly as intended, yet I am a bit puzzled.

I know there is a feed from this URL:  
https://moderaterna.se/ulf-kristersson-och-toppkandidaterna-till-ep-valet-pa-valturne 
(its an example) but your app do not detect it? 

I parse that feed in to another site, and I would like to make sure I parse other feeds from similar sources but with this example I am at a loss. Maybe you can use this example to improve on your detection.

**Comment by shevabam** [comment]
Hello,
The site does not contain an HTML tag specifying an RSS feed (`<link>` tag followed by a specific type).
